"""Generates the console's launcher icons: a tree glyph on the theme's green.

    python tool/generate_icons.py      (from console/, needs Pillow)

Writes the Android adaptive icon (vector foreground + background colour +
legacy PNGs), the web favicon, PWA icons and maskable icons, and the Windows
executable icon (a multi-size .ico, which the installer reuses), all from the
same shapes below, so they never drift apart. The output is committed; run
this again only to change the design.
"""

from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
BACKGROUND = "#2E6B3F"  # yggdrasilSeedColor in lib/app/theme.dart
FOREGROUND = "#FFFFFF"

# The glyph in the 108x108 adaptive-icon canvas; the safe zone is the central
# 66x66 (21..87), and everything below stays inside it.
CIRCLES = [  # (cx, cy, r): the canopy
    (54, 42, 14),
    (42, 50, 11),
    (66, 50, 11),
    (48, 58, 9),
    (60, 58, 9),
]
POLYGONS = [  # the trunk, flaring into roots
    [(51, 56), (57, 56), (57.5, 74), (63, 81), (45, 81), (50.5, 74)],
]


def vector_drawable() -> str:
    paths = []
    for cx, cy, r in CIRCLES:
        paths.append(
            f"M{cx - r},{cy} a{r},{r} 0 1,0 {2 * r},0 a{r},{r} 0 1,0 {-2 * r},0 z"
        )
    for polygon in POLYGONS:
        points = " L".join(f"{x},{y}" for x, y in polygon)
        paths.append(f"M{points} z")
    body = "\n".join(
        f'    <path android:fillColor="{FOREGROUND}" android:pathData="{p}" />'
        for p in paths
    )
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by tool/generate_icons.py. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp" android:height="108dp"\n'
        '    android:viewportWidth="108" android:viewportHeight="108">\n'
        f"{body}\n"
        "</vector>\n"
    )


def render(size: int, *, glyph_scale: float, rounded: bool) -> Image.Image:
    """The icon at [size] px. [glyph_scale] is how much of the image the 108
    canvas covers; a full-bleed maskable icon uses 1, a legacy icon more."""
    ss = 4  # supersampling for smooth edges
    big = size * ss
    image = Image.new("RGBA", (big, big), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    if rounded:
        draw.rounded_rectangle((0, 0, big - 1, big - 1), radius=big * 0.22, fill=BACKGROUND)
    else:
        draw.rectangle((0, 0, big, big), fill=BACKGROUND)

    unit = big / 108 * glyph_scale
    offset = (big - 108 * unit) / 2

    def xy(x: float, y: float) -> tuple[float, float]:
        return (offset + x * unit, offset + y * unit)

    for cx, cy, r in CIRCLES:
        x0, y0 = xy(cx - r, cy - r)
        x1, y1 = xy(cx + r, cy + r)
        draw.ellipse((x0, y0, x1, y1), fill=FOREGROUND)
    for polygon in POLYGONS:
        draw.polygon([xy(x, y) for x, y in polygon], fill=FOREGROUND)

    return image.resize((size, size), Image.LANCZOS)


def main() -> None:
    res = ROOT / "android/app/src/main/res"
    (res / "drawable").mkdir(parents=True, exist_ok=True)
    (res / "drawable/ic_launcher_foreground.xml").write_text(vector_drawable(), newline="\n")

    for density, size in {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}.items():
        render(size, glyph_scale=1.45, rounded=True).save(res / f"mipmap-{density}/ic_launcher.png")

    web = ROOT / "web"
    render(32, glyph_scale=1.5, rounded=True).save(web / "favicon.png")
    render(192, glyph_scale=1.45, rounded=True).save(web / "icons/Icon-192.png")
    render(512, glyph_scale=1.45, rounded=True).save(web / "icons/Icon-512.png")
    # Maskable: full bleed, glyph inside the central 80 % safe zone.
    render(192, glyph_scale=1.0, rounded=False).save(web / "icons/Icon-maskable-192.png")
    render(512, glyph_scale=1.0, rounded=False).save(web / "icons/Icon-maskable-512.png")

    # Windows: every size the shell asks for, from the 16 px title bar to the 256 px tile.
    sizes = [16, 20, 24, 32, 40, 48, 64, 128, 256]
    render(256, glyph_scale=1.45, rounded=True).save(
        ROOT / "windows/runner/resources/app_icon.ico", sizes=[(s, s) for s in sizes]
    )


if __name__ == "__main__":
    main()
